backend:
  name: github
  repo: pajouheshsaraaa/pajouhesh-sara-imaam-ali
  branch: main
  base_url: https://deploy-preview-1--netlify-cms-oauth-provider.netlify.app
  auth_endpoint: auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "news"
    label: "📰 اخبار"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "عنوان خبر", name: "title", widget: "string" }
      - { label: "دسته‌بندی", name: "badge", widget: "string" }
      - { label: "تاریخ", name: "date", widget: "string" }
      - { label: "توضیح کوتاه", name: "excerpt", widget: "text" }
      - { label: "متن کامل", name: "body", widget: "markdown" }